WIP: Add privileged interface
RedHatInsights/patchman-engine pull request #372
Opened 2020-10-09 14:24 UTC by semtexzv

2020-11-19 14:46 UTC, Josca requested changes
looks good, I think I found one forgotten print, thanks

2020-11-19 14:46 UTC, Josca commented on base/utils/identity.go
> +	print(string(decoded))
print?

2020-11-19 14:46 UTC, Josca commented on manager/middlewares/authentication.go
> +		ident, err := utils.ParseIdentity(identStr)
What's the purpose of this change?

2020-11-23 12:09 UTC, semtexzv commented on manager/middlewares/authentication.go
> +		ident, err := utils.ParseIdentity(identStr)
Conflict with package name

2020-11-23 12:57 UTC, Josca approved these changes

2020-11-24 13:12 UTC, merged