added EXCLUDED_REPORTERS option to the listener
RedHatInsights/patchman-engine pull request #421
Opened 2020-11-13 15:19 UTC by Josca

2020-11-13 19:15 UTC, MichaelMraka requested changes

2020-11-18 10:23 UTC, semtexzv approved these changes

2020-11-18 10:24 UTC, Josca commented on listener/listener.go
> +	arr := strings.Split(excludeReportersStr, ";")
ok, updated

2020-11-18 10:32 UTC, MichaelMraka approved these changes

2020-11-18 11:32 UTC, merged