Delete yupana systems
RedHatInsights/patchman-engine pull request #429
Opened 2020-11-24 17:15 UTC by Josca

2020-11-25 08:36 UTC, MichaelMraka requested changes

2020-11-25 08:36 UTC, MichaelMraka commented on database_admin/migrations/046_delete_yupana_systems.up.sql
> +                SELECT deleted + 1 INTO deleted;
deleted := deleted + 1;

2020-11-25 08:36 UTC, MichaelMraka commented on database_admin/migrations/046_delete_yupana_systems.up.sql
> +$$ LANGUAGE plpgsql;
or completely without for loop
```
DO
$$
  DECLARE
      deleted integer;
  BEGIN
     SELECT count(*) INTO deleted FROM (
                    SELECT delete_system(inventory_id) FROM system_platform
                             JOIN reporter r on reporter_id = r.id
                             WHERE r.name = 'yupana' ) x;
     RAISE NOTICE '%', deleted;
  END
$$ LANGUAGE plpgsql;
```

2020-11-26 09:06 UTC, Josca commented on database_admin/migrations/046_delete_yupana_systems.up.sql
> +$$ LANGUAGE plpgsql;
ok, thanks

2020-11-27 09:01 UTC, merged