SPM-991: Fix latest_package_cache view
RedHatInsights/patchman-engine pull request #728
Opened 2021-07-12 09:57 UTC by AlesKas

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2021-07-12 12:25 UTC, AlesKas commented
/retest

2021-07-15 11:31 UTC, Josca requested changes
some conflict appeared, please fix

2021-07-21 12:34 UTC, semtexzv approved these changes

2021-07-21 12:34 UTC, semtexzv commented on database_admin/migrations/066_package_latest_redefine.down.sql
> +DROP MATERIALIZED VIEW IF EXISTS package_latest_cache;
If we run the down migration, it'll delete the view and the refresh task will fail. I'd leave the down migration empty

2021-07-29 13:57 UTC, Josca commented
/retest

2021-08-04 10:26 UTC, Josca approved these changes
Looks good, thanks :+1:

2021-08-04 10:27 UTC, merged