SPM-1061: Manager returns 500 (unknonw system)
RedHatInsights/patchman-engine pull request #750
Opened 2021-07-30 11:30 UTC by AlesKas

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2021-07-30 11:33 UTC, semtexzv approved these changes
Nice and simple fix

2021-07-30 11:53 UTC, Josca requested changes
Great, good job. Just some small updates required.

2021-07-30 11:53 UTC, Josca commented on base/database/utils.go
> +func IsValidUUID(uuid string) bool {
Great, but please put this function to "base/utils/core.go", so we can call it as `utils.IsValidUUID(uuid string) bool`.

2021-07-30 11:53 UTC, Josca commented on manager/controllers/system_advisories_export_test.go
> +func TestUnknownSystemAdvisoriesExport(t *testing.T) {
Please keep test methods name convention "specific part to the end" - here TestSystemAdvisoriesExportUnknown. It makes it easiers to find tests for the same endpoint when printed in logs. Also for other tests.

2021-07-30 11:53 UTC, Josca commented on manager/controllers/system_advisories.go
> +	if !(database.IsValidUUID(inventoryID)) {
You can omit these external brackets - use just `if !utils.IsValidUUID(inventoryID) {`.

2021-07-30 11:53 UTC, Josca commented on base/database/utils.go
> +	r := regexp.MustCompile("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")
This regex can be created in "var" no to be created during each function call. Let's call it e.g. uuidRegex.

~~~golang
var uuidRegex = regexp.MustCompile("^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$")

func IsValidUUID(uuid string) bool {
	return uuidRegex.MatchString(uuid)
}

~~~

2021-08-02 09:26 UTC, Josca approved these changes
Looks good. Thanks :+1:

2021-08-02 09:26 UTC, merged