SPM-1432: fix empty strings in schema
RedHatInsights/patchman-engine pull request #983
Opened 2022-06-20 15:26 UTC by MichaelMraka

## Secure Coding Practices Checklist GitHub Link
- https://github.com/RedHatInsights/secure-coding-checklist

## Secure Coding Checklist
- [x] Input Validation
- [x] Output Encoding
- [x] Authentication and Password Management
- [x] Session Management
- [x] Access Control
- [x] Cryptographic Practices
- [x] Error Handling and Logging
- [x] Data Protection
- [x] Communication Security
- [x] System Configuration
- [x] Database Security
- [x] File Management
- [x] Memory Management
- [x] General Coding Practices

2022-06-20 15:27 UTC, MichaelMraka commented
supersedes #951

2022-06-20 16:48 UTC, psegedy commented
/retest

2022-06-21 10:34 UTC, psegedy commented
please rebase it since it conflicts with already merged #978
```
11:00:13 evaluator/evaluate.go:178:22: invalid operation: system.VmaasJSON == "" (mismatched types *string and untyped string)
```

2022-06-21 10:44 UTC, psegedy commented on database_admin/schema/create_schema.sql
> +    solution         TEXT                     NOT NULL CHECK (NOT empty(solution)),
```
time="2022-06-20T17:19:23Z" level=fatal msg="vmaas data sync failed" err="Failed to sync advisories: Erratas page download and process failed: Storing advisories: Storing advisories: ERROR: new row for relation \"advisory_metadata\" violates check constraint \"advisory_metadata_solution_check\" (SQLSTATE 23514)"
```
either there is a bug in testing data and solution is empty or it is allowed to have empty solution for an erratum

2022-06-21 10:51 UTC, psegedy commented on database_admin/schema/create_schema.sql
> +    solution         TEXT                     NOT NULL CHECK (NOT empty(solution)),
`solution` is not present in epel errata - https://mirror.karneval.cz/pub/linux/fedora/epel/8/Everything/x86_64/repodata/e398dc76062bbd82f69ce299da691f254f13c41d4b93df68a6a4effc8dbee385-updateinfo.xml.bz2

2022-06-22 15:48 UTC, psegedy commented
hm I still see an error with `solution` in logs

>```time="2022-06-22T15:18:25Z" level=fatal msg="vmaas data sync failed" err="Failed to sync advisories: Erratas page download and process failed: Storing advisories: Storing advisories: ERROR: new row for relation \"advisory_metadata\" violates check constraint \"advisory_metadata_solution_check\" (SQLSTATE 23514)"```

2022-06-23 16:40 UTC, psegedy requested changes

2022-06-23 16:42 UTC, psegedy commented on base/models/models.go
> +	Solution        *string
maybe the `gorm:"default:null"` should be here  😄

2022-06-27 09:03 UTC, merged